// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://athfqixuwxophhqlujde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aGZxaXh1d3hvcGhocWx1amRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjg2MDMsImV4cCI6MjA2MDg0NDYwM30.aPAk9pRpQEGixgt0wGGxn6kQ-IEwkV2ZZXnLd_JBuSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);